server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/java
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rootPassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #hibernate query ??? ??
        show_sql: true #hibernate query? ??? ??

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

