server:
  port: 80

# ?????? ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/java
    username: root
    password: rootPassword

# Entity? ??? ??? ????? ?? ??
  #create(??? ? ??? ?? ??)
  #create-drop(??? ? ??, ??? ? ??)
  #update(???? ??)
  #validate(??? ??)
  #none(???? ??)
  jpa:
    hibernate:
      ddl-auto: update
# show_sql ? sql ?? ??
# format_sql ? ?? ???? ??
    properties:
      hibernate:
        format-sql: true
        show_sql: true
# ?? ?? ???? ? ? ?? ??
logging:
  level:
    org.hibernate.type.description.sql: trace